//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace transcodeFF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\srcPath")]
        public string srcPath {
            get {
                return ((string)(this["srcPath"]));
            }
            set {
                this["srcPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\destPath")]
        public string destPath {
            get {
                return ((string)(this["destPath"]));
            }
            set {
                this["destPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-c:v libx264 -strict -2 -s 1920*1080 -b 8000k -ab 128k  -r 25  -vf pad=\"ih*16/9/s" +
            "ar:ih:(ow-iw)/2:(oh-ih)/2\" ")]
        public string SDarguments {
            get {
                return ((string)(this["SDarguments"]));
            }
            set {
                this["SDarguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\errorPath")]
        public string errorPath {
            get {
                return ((string)(this["errorPath"]));
            }
            set {
                this["errorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-vcodec mpeg2video -s 1920x1080 -b:v 50000k -maxrate 50000k -bufsize 3835k -minra" +
            "te 50000k -r 25 -flags ilme -top 1 -acodec pcm_s24le -ar 48000 -pix_fmt yuv422p " +
            "-profile:v 0 -level:v 2  -map 0:v  -map 0:a")]
        public string XDCAMarguments1 {
            get {
                return ((string)(this["XDCAMarguments1"]));
            }
            set {
                this["XDCAMarguments1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int scanInterval {
            get {
                return ((int)(this["scanInterval"]));
            }
            set {
                this["scanInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int textclearLength {
            get {
                return ((int)(this["textclearLength"]));
            }
            set {
                this["textclearLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".mxf")]
        public string XDCAMextension {
            get {
                return ((string)(this["XDCAMextension"]));
            }
            set {
                this["XDCAMextension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("muxing overhead:")]
        public string xdcamsuccessString {
            get {
                return ((string)(this["xdcamsuccessString"]));
            }
            set {
                this["xdcamsuccessString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transcode01")]
        public string transcodeExe {
            get {
                return ((string)(this["transcodeExe"]));
            }
            set {
                this["transcodeExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Weighted P-Frames:")]
        public string h264successString {
            get {
                return ((string)(this["h264successString"]));
            }
            set {
                this["h264successString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-c:v libx264 -strict -2 -s 1920*1080 -b 8000k  -ab 128k -r 25  ")]
        public string H264HDarguments {
            get {
                return ((string)(this["H264HDarguments"]));
            }
            set {
                this["H264HDarguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".mp4")]
        public string H264extension {
            get {
                return ((string)(this["H264extension"]));
            }
            set {
                this["H264extension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IFH264 {
            get {
                return ((bool)(this["IFH264"]));
            }
            set {
                this["IFH264"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15592573")]
        public int bitRate {
            get {
                return ((int)(this["bitRate"]));
            }
            set {
                this["bitRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-vcodec mpeg2video -s 1920x1080 -b:v 50000k -maxrate 50000k -bufsize 3835k -minra" +
            "te 50000k -r 25 -flags ilme -top 1 -acodec pcm_s24le -ar 48000 -pix_fmt yuv422p " +
            "-profile:v 0 -level:v 2 -map 0:v")]
        public string XDCAMarguments2 {
            get {
                return ((string)(this["XDCAMarguments2"]));
            }
            set {
                this["XDCAMarguments2"] = value;
            }
        }
    }
}
